### ISSUE TITLE
Cannot tie out with bitcoincash's examples

### ISSUE THREAD

**Issue by kushal256** [sealedtx/bitcoin-cash-converter#1]
I really like this project!

Was trying to tie out results from the examples at https://github.com/bitcoincashorg/bitcoincash.org/blob/master/spec/cashaddr.md#examples-of-address-translation

The first two examples work, but the last three do not.

**Comment by sealedtx** [comment]
Hello, @kushal256 !
My bad, forgot to add version check (P2SH or P2PKH).
Fixed!

**Comment by kushal256** [comment]
Awesome thanks @sealedtx ! 

I tested all the examples listed and they work now, thanks (I noticed you didn't add all the examples in your test cases?)

Also thx for adding the pom.xml, will allow me to now use https://jitpack.io/#sealedtx/bitcoin-cash-converter/master-SNAPSHOT so I can easily integrate with my own gradle project.  Would you mind tagging the project within github to some version number?  That way I don't have to refer to 'com.github.sealedtx:bitcoin-cash-converter:master-SNAPSHOT', I can tie to a specific version of your project.

**Comment by sealedtx** [comment]
@kushal256 I added only one address of each version as i mentioned before there is difference in converting P2SH and P2PKH. Tag 1.0 added. You're welcome:
implementation 'com.github.sealedtx:bitcoin-cash-converter:1.0'

**Comment by kushal256** [comment]
Thanks, closing this issue
